lab0 done
OneClock1/OOP_Labs pull request #1
Opened 2023-03-01 20:57 UTC by OneClock1

2023-03-02 12:23 UTC, RuslanSlobodian requested changes

2023-03-02 12:23 UTC, RuslanSlobodian commented on LAB0/src/Main.java
> +        System.out.printf(" %tY", dat);
Чому розділив вивід дати аж на три printf?

2023-03-02 12:23 UTC, RuslanSlobodian commented on LAB0/src/Main.java
> +    private void date ()
назви методів мають починатись із дієслова і описувати ту роботу, яку вони виконують

2023-03-02 12:23 UTC, RuslanSlobodian commented on LAB0/src/Main.java
> +        double s = Math.pow(Math.tan(Math.pow(x, 3)), 2) * Math.pow((x + b),2) + a / Math.sqrt(x + b);
Обчислення значень S і Q має відбуватись в двох окремих методах, наприклад:
calculateS i CalculateQ

2023-03-02 12:23 UTC, RuslanSlobodian commented on LAB0/src/Main.java
> +    private void run(double a, double b, double x)
назва методу не дає чіткого розуміння того, що ж він робить

2023-03-02 12:23 UTC, RuslanSlobodian commented on LAB0/src/Main.java
> +    private void calculator () {
назви методів мають починатись із дієслова і описувати ту роботу, яку вони виконують

2023-03-06 12:08 UTC, OneClock1 commented on LAB0/src/Main.java
> +        System.out.printf(" %tY", dat);
+

2023-03-06 12:08 UTC, OneClock1 commented on LAB0/src/Main.java
> +    private void date ()
+

2023-03-06 12:08 UTC, OneClock1 commented on LAB0/src/Main.java
> +        double s = Math.pow(Math.tan(Math.pow(x, 3)), 2) * Math.pow((x + b),2) + a / Math.sqrt(x + b);
+

2023-03-06 12:08 UTC, OneClock1 commented on LAB0/src/Main.java
> +    private void run(double a, double b, double x)
+

2023-03-06 12:08 UTC, OneClock1 commented on LAB0/src/Main.java
> +    private void calculator () {
+

2023-03-06 12:32 UTC, OneClock1 commented
+

2023-03-06 13:50 UTC, RuslanSlobodian approved these changes

2023-03-06 13:51 UTC, merged